node() {

    // You need to have the provider 'Red Hat UMB Stage' defined
    // in your global config
    //
def triggerCount = 100
for (int i = 0; i < triggerCount; i++) {
    def sendResult = sendCIMessage providerName: 'Red Hat UMB Stage', \
    overrides: [topic: 'VirtualTopic.eng.ci.example.durable.test'], \
                    messageType: 'Custom', \
                    messageProperties: """ 
    action=${i}
                    """, \
                    messageContent: """
                      {
    
    "action": "${i}"
  }
                    """
  // echo sent message id and content
  echo sendResult.getMessageId()
  echo sendResult.getMessageContent()
}
}

